# Generated by Django 2.0.9 on 2019-01-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='text',
        ),
    ]
