# Generated by Django 2.0.9 on 2019-01-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_recipe_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=''),
        ),
    ]
