# Generated by Django 2.0.9 on 2019-01-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20190105_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='', verbose_name='framgangsmate'),
        ),
    ]
