# Generated by Django 2.0.9 on 2019-01-08 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20190106_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField(default='')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 1, 8, 16, 44, 8, 55304, tzinfo=utc))),
                ('approved_comment', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.Recipe')),
            ],
        ),
    ]
