# Generated by Django 2.0.9 on 2019-04-29 19:08

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20190201_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 19, 8, 34, 316429, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=ckeditor.fields.RichTextField(verbose_name='ingredienser'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=ckeditor.fields.RichTextField(default='', verbose_name='framgangsmate'),
        ),
    ]
